### ISSUE TITLE
Push mmpdb 3.1 to PyPI

### ISSUE THREAD

**Issue by ESRE-dev** [rdkit/mmpdb#68] opened 2024-11-11 14:35 UTC
When `pip` installing `mmpdb`, only version 2.1 is available. Please push the latest version 3.1 to PyPI.

**Comment by adalke** [comment] 2024-11-11 16:26
> On Nov 11, 2024, at 15:35, Emanuel Ehmki ***@***.***> wrote:
> 
> When pip installing mmpdb, only version 2.1 is available. Please push the latest version 3.1 to PyPI.

This is a duplicate of #58 .

                                Andrew
                                ***@***.***

**Closed as completed** 2024-11-12 05:47 UTC
